/* 
 * Xero AppStore API
 *
 * These endpoints are for Xero Partners to interact with the App Store Billing platform
 *
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

// The version of the OpenAPI document: 2.21.0


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Xero.Net.Api.Client;
using Xero.Net.Api.Model.Appstore;

namespace Xero.Net.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAppStoreApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves a subscription for a given subscriptionId
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Xero.Net.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accessToken">Xero API OAuth 2.0 accessToken</param>
        /// <param name="subscriptionId">Unique identifier for Subscription object</param>
        /// <returns>Task of Subscription</returns>
        System.Threading.Tasks.Task<Subscription> GetSubscriptionAsync(string accessToken, Guid subscriptionId);

        /// <summary>
        /// Retrieves a subscription for a given subscriptionId
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Xero.Net.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accessToken">Xero API OAuth 2.0 accessToken</param>
        /// <param name="subscriptionId">Unique identifier for Subscription object</param>
        /// <returns>Task of ApiResponse (Subscription)</returns>
        System.Threading.Tasks.Task<ApiResponse<Subscription>> GetSubscriptionAsyncWithHttpInfo(string accessToken, Guid subscriptionId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAppStoreApi : IAppStoreApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AppStoreApi : IAppStoreApi
    {
        private Xero.Net.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AppStoreApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AppStoreApi() : this((string)null)
        {
            this.Configuration = Xero.Net.Api.Client.Configuration.MergeConfigurations(
                Xero.Net.Api.Client.GlobalConfiguration.Instance,
                new Xero.Net.Api.Client.Configuration { BasePath = "https://api.xero.com/appstore/2.0" }
            );
            this.AsynchronousClient = new Xero.Net.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Xero.Net.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AppStoreApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AppStoreApi(String basePath)
        {
            this.Configuration = Xero.Net.Api.Client.Configuration.MergeConfigurations(
                Xero.Net.Api.Client.GlobalConfiguration.Instance,
                new Xero.Net.Api.Client.Configuration { BasePath = basePath }
            );
            this.AsynchronousClient = new Xero.Net.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Xero.Net.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AppStoreApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AppStoreApi(Xero.Net.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Xero.Net.Api.Client.Configuration.MergeConfigurations(
                Xero.Net.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.AsynchronousClient = new Xero.Net.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Xero.Net.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AppStoreApi(Xero.Net.Api.Client.ISynchronousClient client, Xero.Net.Api.Client.IAsynchronousClient asyncClient, Xero.Net.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Xero.Net.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Xero.Net.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Xero.Net.Api.Client.IReadableConfiguration Configuration { get; set; }


        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Xero.Net.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }


        /// <summary>
        /// Retrieves a subscription for a given subscriptionId 
        /// </summary>
        /// <exception cref="Xero.Net.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accessToken">Xero API OAuth 2.0 accessToken</param>
        /// <param name="subscriptionId">Unique identifier for Subscription object</param>
        /// <returns>Task of Subscription</returns>
        public async System.Threading.Tasks.Task<Subscription> GetSubscriptionAsync(string accessToken, Guid subscriptionId)
        {
            Xero.Net.Api.Client.ApiResponse<Subscription> localVarResponse = await GetSubscriptionAsyncWithHttpInfo(accessToken, subscriptionId);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a subscription for a given subscriptionId 
        /// </summary>
        /// <exception cref="Xero.Net.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accessToken">Xero API OAuth 2.0 accessToken</param>
        /// <param name="subscriptionId">Unique identifier for Subscription object</param>
        /// <returns>Task of ApiResponse (Subscription)</returns>
        public async System.Threading.Tasks.Task<Xero.Net.Api.Client.ApiResponse<Subscription>> GetSubscriptionAsyncWithHttpInfo(string accessToken, Guid subscriptionId)
        {
            // verify the required parameter 'subscriptionId' is set
            if (subscriptionId == null)
                throw new Xero.Net.Api.Client.ApiException(400, "Missing required parameter 'subscriptionId' when calling AppStoreApi->GetSubscription");


            Xero.Net.Api.Client.RequestOptions requestOptions = new Xero.Net.Api.Client.RequestOptions();

            String[] @contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] @accepts = new String[] {
                "application/json"
            };

            foreach (var cType in @contentTypes)
                requestOptions.HeaderParameters.Add("Content-Type", cType);

            foreach (var accept in @accepts)
                requestOptions.HeaderParameters.Add("Accept", accept);

            if (subscriptionId != null)
                requestOptions.PathParameters.Add("subscriptionId", Xero.Net.Api.Client.ClientUtils.ParameterToString(subscriptionId)); // path parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(accessToken))
            {
                requestOptions.HeaderParameters.Add("Authorization", "Bearer " + accessToken);
            }
            // make the HTTP request



            var response = await this.AsynchronousClient.GetAsync<Subscription>("/subscriptions/{subscriptionId}", requestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("GetSubscription", response);
                if (exception != null) throw exception;
            }

            return response;
        }

    }
}
